### ISSUE TITLE
 Objects are not valid as a React child (found: object with keys {children})

### ISSUE THREAD

**Issue by aroshanzamir** [jmarioste/next-multiple-layouts-tutorial#2]
Thank you for the tutorial. When I run the project, I got the following error...

`Error: Objects are not valid as a React child (found: object with keys {children}). If you meant to render a collection of children, use an array instead.`

Complete Error:
```
Error: Objects are not valid as a React child (found: object with keys {children}). If you meant to render a collection of children, use an array instead.
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6179:11)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderIndeterminateComponent (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (E:\Nextjs\next-samples\with-page-template\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
```

**Comment by ShaileshGodghase** [comment]
The same error occurred to me as well. Have you found a solution yet?

**Comment by jmarioste** [comment]
Here's the solution: https://github.com/jmarioste/next-multiple-layouts-tutorial/issues/1#issuecomment-1407509706

**Comment by ShaileshGodghase** [comment]
@jmarioste 
I think the error occurs because of `Layouts[Component.Layout]` is sometimes undefined. I solved this problem by adding this.
```
  if (Layouts[Component.Layout] == undefined) {
    return <Component {...pageProps} />;
  }
```
my `_app.tsx`
```
export default function App({ Component, pageProps }: MyAppProps) {
  if (Layouts[Component.Layout] == undefined) {
    return <Component {...pageProps} />;
  }
  const Layout = Layouts[Component.Layout] ?? ((page: ReactNode) => page);

  return (
    <>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
```

**Comment by vipertecpro** [comment]
> @jmarioste I think the error occurs because of `Layouts[Component.Layout]` is sometimes undefined. I solved this problem by adding this.
> 
> ```
>   if (Layouts[Component.Layout] == undefined) {
>     return <Component {...pageProps} />;
>   }
> ```
> 
> my `_app.tsx`
> 
> ```
> export default function App({ Component, pageProps }: MyAppProps) {
>   if (Layouts[Component.Layout] == undefined) {
>     return <Component {...pageProps} />;
>   }
>   const Layout = Layouts[Component.Layout] ?? ((page: ReactNode) => page);
> 
>   return (
>     <>
>       <Layout>
>         <Component {...pageProps} />
>       </Layout>
>     </>
>   );
> }
> ```

Yeap this resolved the issue, thx alot brother

**Comment by jmarioste** [comment]
@ShaileshGodghase  Thanks for your solution. Will close this issue.
